version: "3"
services:
  flask:
    build: "./backend"
    ports:
      - "5000:5000"
  frontend:
    build: 
      context: "./frontend"
      args:
        - VUE_APP_API_URL=flask
    ports:
      - "80:80"

