version: "3"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
  frontend:
    build: 
      context: "./frontend"
      args:
        - VUE_APP_API_URL=http://localhost:5000
    ports:
      - "80:80"

