version: "3"
services:
  flask:
    build: 
      context: "./backend"
      args:
        - DB_PATH=/usr/src/app/./sqlfiles/practice-app.db
    ports:
      - "5000:5000"
  frontend:
    build: 
      context: "./frontend"
      args:
        - VUE_APP_API_URL=18.184.69.221:5000
    ports:
      - "80:80"

