version: '3'

services:
  db-server:
    image: "postgres"
    container_name: "db-server"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beabee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
    networks:
      - beabeenw
  beabee-server:
    image: "beabeeapp/beabee"
    container_name: "beabee-server"
    ports:
      - "8085:8085"
    environment:
      spring.datasource.url: jdbc:postgresql://db-server:5432/beabee
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 5432
    networks:
      - beabeenw
    depends_on:
      - db-server
    restart: always
networks:
  beabeenw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '10.111.6.0/24'
